config/routes.rb
Hackathon::Application.routes.draw do

  root to: 'site#index'

  # Registration
  resources :users, only: [:new, :create]
  get 'signup' => 'users#new', as: 'signup'

  # Authentication
  get 'login' => 'sessions#new', as: 'login'
  delete 'logout' => 'sessions#destroy', as: 'logout'

  # Restful resources
  resources :sessions, only: [:new, :create, :destroy]
  resources :issues, only: [:index, :show, :new, :create] do
    resources :comments, only: :create
  end
end

app/models/city.rb
class City < ActiveRecord::Base
  # Associations
  has_many :issues

  # Validations
  validates :name, :subdomain, :country, :latitude, :longitude, presence: true
  validates :latitude, :longitude, numericality: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  # Associations
  belongs_to :user
  belongs_to :issue
  has_many :photos, as: :imageable, dependent: :delete_all

  # Validations
  validates :content, presence: true
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  CLOSED = 0
  OPEN = 1
  STATUSES = [OPEN, CLOSED]

  # Associations
  belongs_to :creator, class_name: "User"
  belongs_to :assignee, class_name: "User"
  belongs_to :city
  has_many :comments
  has_many :photos, as: :imageable, dependent: :delete_all
  has_many :issue_labels, dependent: :delete_all
  has_many :labels, through: :issue_labels

  # Validations
  validates :title, :description, presence: true
  validates :latitude, numericality: true, if: :latitude
  validates :longitude, numericality: true, if: :longitude

  # Methods
  def add_labels(label_ids)
    return unless label_ids
    label_ids.each do |label_id|
      self.issue_labels.create(label_id: label_id)
    end
  end
end

app/models/issue_label.rb
class IssueLabel < ActiveRecord::Base
  # Associations
  belongs_to :issue
  belongs_to :label
end

app/models/label.rb
class Label < ActiveRecord::Base
  # Associations
  has_many :issue_labels, dependent: :delete_all
  has_many :issues, through: :issue_labels

  # Validations
  validates :name, :color, presence: true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  # Associations
  belongs_to :imageable, :polymorphic => true

  # Validations
  validates :image, :imageable_type, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  #Associations
  has_many :reported_issues, class_name: "Issue", foreign_key: "creator_id"
  has_many :assigned_issues, class_name: "Issue", foreign_key: "assignee_id"
  has_many :comments

  #Validations
  validates :username, :email, :password, presence: true
  validates :username, :email, uniqueness: {case_sensitive: false}
  validates :username, format: { with: /\A[\w-]+\z/ }
  validates :email, format: { with: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i }

  #Methods
  def self.find_by_email_or_username(email_or_username)
    find_by_email(email_or_username) || find_by_username(email_or_username)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authorize
    redirect_to login_url, alert: "Not authorized" unless current_user
  end

  private
  def logged_in?
    !!current_user
  end
  helper_method :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def redirect_if_logged_in
    redirect_to :issues if logged_in?
  end
  helper_method :redirect_if_logged_in
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authorize, only:  [:create]

  def create
    @issue = Issue.find(params[:issue_id])
    @comment = @issue.comments.new(comment_params)

    if @comment.save
      redirect_to @issue
    else
      render @issue
    end
  end

  protected

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_filter :authorize, only:  [:new, :create]

  def index
    @issues = Issue.all
  end

  def show
    @issue = Issue.find(params[:id])
    @comments = @issue.comments
  end

  def new
    @issue = Issue.new(params[:issue])
    @labels = Label.all
  end

  def create
    @issue = current_user.reported_issues.new(issues_params)
    if @issue.save
      @issue.add_labels(params[:issue][:labels])
      render @issue
    else
      @labels = Label.all
      flash.now.alert = "Verify the info before of continue."
      render 'new'
    end
  end

  private
  def issues_params
    params.require(:issue).permit(:title, :description, :assignee_id, :latitude, :longitude)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :authorize, only: :destroy
  before_filter :redirect_if_logged_in, except: :destroy

  def new
  end

  def create
    user = User.find_by_email_or_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to :issues, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  before_filter :redirect_if_logged_in
  
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :redirect_if_logged_in

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to :issues, notice: "Thank you for signing up!"
    else
      flash.now.alert = "Please verify your info."
      render "new"
    end
  end

  protected

  def user_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :company, :url, :location)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
  def collaborators_list
    collaborators_list ||= User.where(collaborator: true).map { |colaborator| [colaborator.name, colaborator.id] }
  end
end

app/views/issues/_form.html.erb
<%= form_for @issue do |f| %>
  <div class="field">
    <%= f.text_field :title, class: "edit", placeholder: "title" %>
  </div>
  <% unless @issue.errors[:title].blank? %>
    <span class="field-error"><%= @issue.errors[:title].first %>.</span>
  <% end %>
  <div class="field">
    <%= f.text_area :description, class: "edit", placeholder: "description" %>
  </div>
  <% unless @issue.errors[:description].blank? %>
    <span class="field-error"><%= @issue.errors[:description].first %>.</span>
  <% end %>
  <div class="field">
    <%= f.select :assignee_id, options_for_select(collaborators_list), class: "edit", prompt: "- Select a responsable -" %>
  </div>
  <% unless @issue.errors[:assignee_id].blank? %>
    <span class="field-error"><%= @issue.errors[:asignee_id].first %>.</span>
  <% end %>
  <% @labels.each do |label| %>
    <%= check_box_tag 'issue[labels][]',  label.id, false %>
    <%= label.name %>
  <% end %>
  <div class="actions">
    <%= f.submit "Add Issue", class: "btn flat" %>
    <%= link_to "Cancel", "#", class: "btn flat green" %>
  </div>
<% end %>

app/views/issues/_issue.html.erb
<h2><%= issue.title %></h2>
<p><%= issue.description %></p>

app/views/issues/index.html.erb
<%= content_for :title do %>
  <title>Citissuer | Issues</title>
<% end %>

<h2>Issues of your city</h2>
<div class="map">
</div>
<% @issues.each do |issue| %>
  <%= link_to issue.title, issue %>
<% end %>

app/views/issues/new.html.erb
<%= content_for :title do %>
  <title>Citissues | New Issue</title>
<% end %>
<h2>Report Issue</h2>
<%= render 'form' %>

app/views/issues/show.html.erb
<%= content_for :title do %>
  <title>Citissues | <%= @issue.title %></title>
<% end %>
<%= render @issue %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= yield :title %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "site" %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body>
    
     <div class="container-narrow">
        <div class="masthead">
          <ul class="nav nav-pills pull-right">
            <% unless logged_in? %>
              <li class="active"><%= link_to "Home", root_path %></li>
              <li><%= link_to "Sign up", signup_path %></li>
              <li><%= link_to "Sign in", login_path %></li>
            <% else %>
              <li><%= link_to "New Issue", new_issue_path %></li>
              <li><%= link_to "Logout", logout_path, method: :delete %></li>
            <% end %>
          </ul>
          <h3>Citissuer</h3>
        </div>
        <hr>
	    <%= yield %>
        <hr>
        <div class="footer">
          <p>© Citissuer 2013</p>
        </div> 
    
      </div> <!-- /container -->
	</body>

</body>
</html>

app/views/site/index.html.erb
<%= content_for :title do %>
  <title>Citissuer | Home</title>
<% end %>
<div class="jumbotron">
  <h1>Issues of your city</h1>
  <div class="map">
  </div>
  <p class="lead">Report, socialize and collaborate to solve the issues of your city.</p><p class="lead">Make of your city a better place to live, from your movile or your desktop</p>
  <%= link_to "Sign up now", signup_path, class: "btn btn-large btn-success" %>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
	<div class="field">
		<%= f.text_field :username, class: "edit", placeholder: "Username" %>
	</div>
	<% unless @user.errors[:username].blank? %>
		<span class="field-error"><%= @user.errors[:username].first %>.</span>
	<% end %>
	<div class="field">
		<%= f.email_field :email, class: "edit", placeholder: "Email" %>
	</div>
	<% unless @user.errors[:email].blank? %>
		<span class="field-error"><%= @user.errors[:email].first %>.</span>
	<% end %>
	<div class="field">
		<%= f.password_field :password, class: "edit", placeholder: "Password" %>
	</div>
	<% unless @user.errors[:password].blank? %>
		<span class="field-error"><%= @user.errors[:password].first %>.</span>
	<% end %>
	<div class="field">
		<%= f.password_field :password_confirmation, class: "edit", placeholder: "Confirm password" %>
	</div>
	<% unless @user.errors[:password_confirmation].blank? %>
		<span class="field-error"><%= @user.errors[:password_confirmation].first %>.</span>
	<% end %>
	<div class="clearfix"></div>
	<div class="actions">
		<%= f.submit "Sign up", class: "btn flat" %>
		<%= link_to "Back to Home", :root, id:"back-to-plans-btn", class: "btn flat green" %>
	</div>
<% end %>